version: "3.8"

services:
  event-bus:
    build:
      context: ./src/event_bus
      args:
        - PORT_IN=5555
        - PORT_OUT=5556
        - LOG_LEVEL=info
    ports:
      - 5555:5555
      - 5556:5556
    environment:
      - LOG_LEVEL=debug
    networks:
      - ai-smart-mirror

networks:
  ai-smart-mirror:
    name: ai-smart-mirror
